language: node_js
node_js:
  - "11"
scripts:
  - npm install react react-router-dom @emotion/styled @emotion/core
  - npm run ci
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
